### ISSUE TITLE
Example with Babel 6

### ISSUE THREAD

**Issue by markgandy** [reindexio/reindex-examples#2]
Hi, do you have any examples with Babel 6? I have something working with babel 5, but it breaks when I upgrade to babel 6.

```
Uncaught Error: Invariant Violation: RelayQL: Unexpected invocation at runtime. Either the Babel transform was not set up, or it failed to identify this call site. Make sure it is being used verbatim as `Relay.QL`.
```

**Comment by markgandy** [comment]
Here is how to reproduce. The babel-5 branch works, but get the error above with babel-6 branch. Maybe I am missing something on how to configure babel-6?

https://github.com/markgandy/react-starter/tree/feature/reindex-babel5
https://github.com/markgandy/react-starter/tree/feature/reindex-babel6

**Comment by freiksenet** [comment]
I've never tried babel-relay-plugin-loader, but I think the problem is in it not getting loaded. It seems to [log into console](https://github.com/BerndWessels/babel-relay-plugin-loader/blob/master/index.js#L20), do you get anything like that in your compilation log?

**Comment by freiksenet** [comment]
Otherwise we have, eg, react-native starter using Babel 6. You can try using babel-relay-plugin directly, instead of using a loader.

**Comment by markgandy** [comment]
I do get the console log:

`babel-relay-plugin-loader: using schema at [/home/mark/Dev/markgandy/react-starter/data/schema.json]`

I am using the babel-relay-plugin-loader as I was getting this issue when using babel-relay-plugin directly:
https://phabricator.babeljs.io/T2474

I will try again to get it working with babel-relay-plugin directly, but the loader plugin does work fine in the babel5 branch so I'm a bit confused.

I will also take a look at the react-native starter.

Thanks @freiksenet

**Comment by freiksenet** [comment]
I've found the issue.

`webpack.config.babel.js` seems to ignore/override plugin definition in .babelrc. When I've added plugins configuration there, it worked.

**Comment by freiksenet** [comment]
In `webpack.config.babel.js`

``` js
export const module = {
  loaders: [
    {
      test: /\.js$/,
      exclude: /node_modules/,
      loader: 'babel',
      query: {
        presets: ['react', 'es2015', 'stage-0'],
        plugins: ['babel-relay-plugin-loader']
      },
    },
  ],
};

```

**Comment by markgandy** [comment]
Yes, thank you.
Sorry, I knew it would be something simple!
